repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        args: ["--show-config"]
        types:
          - python
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types:
          - python