services:
  redis:
    image: redis:latest
    env_file:
      - '.env'
    command: redis-server
    expose:
      - ${REDIS_PORT}
    volumes:
      - test_redis_data:/data

  backend:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "sleep 5 && uv run pytest -v"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./app:/app/app

volumes:
  test_db_data:
  test_redis_data: