entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'

log:
  level: INFO
accessLog: {}
providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  le:
    acme:
      email: <your email here>
      storage: /le/acme.json
      httpChallenge:
        entryPoint: web
